In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
 arr= np.array((1,3,4,45,5))
print(arr)
print(type(arr))

[ 1  3  4 45  5]
<class 'numpy.ndarray'>


0 dimension Array

In [5]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1 dimension array

In [10]:
arr=np.array([2,4,5,3])
print(arr)
print(arr.ndim)

[2 4 5 3]
1


2 Dimension Array

In [7]:
arr=np.array([[1,3,4],[32,4,5]])
print(arr.ndim)

2


In [8]:
print(arr)

[[ 1  3  4]
 [32  4  5]]


3 d array

In [12]:
arr= np.array([[[2,3,4,5],[3,4,5,5],[3,4,5,5]]])
print(arr)
print(arr.ndim)

[[[2 3 4 5]
  [3 4 5 5]
  [3 4 5 5]]]
3


ANOTHER METHODD TO CREATE N DIMENSIONAL ARRAY

In [13]:
arr= np.array([1,3,4,4],ndmin=5)
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[1 3 4 4]]]]]
<class 'numpy.ndarray'>
5


INDEXING IN ARRAY

In [14]:
arr= np.array([32,3,4,5,5,3,3,4])
print(arr[-1])

4


In [15]:
print(arr[-2])

3


In [16]:
print(arr[4])

5


In [17]:
arr=np.array([[3,4,4,0],[3,4,5,5]])
print(arr[0,1])

4


In [18]:
print(arr[1,3])

5


Add the first element of Row 1 and last element

In [25]:
print("sum is: " , (arr[0,0]+arr[1,3]))

sum is:  8


In [26]:
arr= np.array([[[1,3,4,5],[3,4,4,5],[3,3,4,5]]])
print(arr)

[[[1 3 4 5]
  [3 4 4 5]
  [3 3 4 5]]]


In [27]:
print(arr[0,0,1])

3


#@SLICING OF NUMPY ARRAY

In [29]:
arr= np.array([3,4,4,5,6])
print(arr[1:4])

[4 4 5]


In [31]:
arr=np.array([[3,4,5,5],[3,4,5,4]])
print(arr[1][1:4])

[4 5 4]


In [38]:
arr=np.array([[[1,3,4,5],[3,3,0,5]],[[3,3,4,5],[3,3,2,6]]])
print(arr)

[[[1 3 4 5]
  [3 3 0 5]]

 [[3 3 4 5]
  [3 3 2 6]]]


In [41]:
print(arr[1,0,0:4])

[3 3 4 5]


DATA TYPES IN NUMPY

i-INTEGER
b-Boolean
u-unsigned integer
c-complex float
m-timedelta
M-datetime
O-object
S-string
U-unicode string
V-fixed chunk of memory for other type ( void )

In [42]:
arr=np.array([3,43,5,5])
print(arr.dtype)

int32


In [43]:
arr=np.array(['andin','asjdf','skdf'])
print(arr.dtype)

<U5


Creating arrays with a defined data type

In [46]:
arr=np.array([2,2,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'2' b'2' b'4' b'5']
|S1


create an array with data types 4 bytes integer

In [48]:
arr=np.array([2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[2 3 4 5]
int32


Numpy Array Shape

print the shape of 2d array

In [49]:
arr= np.array([3,43,5,50])
print(arr.shape)

(4,)


In [50]:
arr= np.array([[3,4,4,5],[3,3,3,4]])
print(arr.shape)

(2, 4)


In [51]:
arr = np.array([[[3,3,45,3],[3,3,3,3]]])
print(arr.shape)

(1, 2, 4)


Joining Numpy Arrays

In [53]:
arr1= np.array([1,3,4,5])
arr2 = np.array([2,3,4,5])

arr=np.concatenate((arr1,arr2))

print(arr)

[1 3 4 5 2 3 4 5]


Join 2d array

In [55]:
arr1= np.array([[23,3,4,4],[3,3,3,4]])
arr2= np.array([[23,3,34,4],[3,3,3,5]])

arr= np.concatenate((arr1,arr2),axis=1)
print(arr)

[[23  3  4  4 23  3 34  4]
 [ 3  3  3  4  3  3  3  5]]


In [56]:
arr1= np.array([[23,3,4,4],[3,3,3,4]])
arr2= np.array([[23,3,34,4],[3,3,3,5]])

arr= np.concatenate((arr1,arr2),axis=0)
print(arr)

[[23  3  4  4]
 [ 3  3  3  4]
 [23  3 34  4]
 [ 3  3  3  5]]


splitting numpy arrays

spliting the array in 3 parts 

In [61]:
arr=np.array([1,3,4,5,5,5,6,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 3, 4]), array([5, 5, 5]), array([6, 6])]


spliting the array in 4 parts

In [62]:
arr=np.array([1,3,4,5,5,5,6,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 3]), array([4, 5]), array([5, 5]), array([6, 6])]


Ravel and Flatten:-
converts multidimensional arrayvinto 1d array

In [69]:
m=np.array([[2,3,45,4],[3,3,3,3]])
print(m)
print("dimension IS : " ,m.ndim)

# n=m.ravel
p=m.flatten()
print(p)
# print(n)

print("Now the new dimension is : ",p.ndim)



[[ 2  3 45  4]
 [ 3  3  3  3]]
dimension IS :  2
[ 2  3 45  4  3  3  3  3]
Now the new dimension is :  1


Unique Function 

In [71]:
k= np.array([1,2,3,4,5,3,22,3,34,23,2,23])

print(k)

x= np.unique(k)
print(x)

[ 1  2  3  4  5  3 22  3 34 23  2 23]
[ 1  2  3  4  5 22 23 34]


In [72]:
k= np.array([1,2,3,4,5,3,22,3,34,23,2,23])

print(k)

x= np.unique(k,return_index = True)
print(x)

[ 1  2  3  4  5  3 22  3 34 23  2 23]
(array([ 1,  2,  3,  4,  5, 22, 23, 34]), array([0, 1, 2, 3, 4, 6, 9, 8], dtype=int64))


In [74]:
k= np.array([1,2,3,4,5,3,22,3,34,23,2,23])

print(k)

x= np.unique(k,return_index = True, return_counts= True)
print(x)

[ 1  2  3  4  5  3 22  3 34 23  2 23]
(array([ 1,  2,  3,  4,  5, 22, 23, 34]), array([0, 1, 2, 3, 4, 6, 9, 8], dtype=int64), array([1, 2, 3, 1, 1, 1, 2, 1], dtype=int64))


Delete 

In [78]:
arr = np.array([23,2,32,3,34,4])

d= np.delete(arr,[2])
d

array([23,  2,  3, 34,  4])

In [82]:
x= np.array([[23,3,4,5],[3,3,2,2]])

d= np.delete(x,1,axis=0)
d

array([[23,  3,  4,  5]])